## tl;dr

- Nasdaq Legacy positioning is the clearest contrarian upside signal: non-commercial net exposure is at the 6.8th percentile.
- Nasdaq TFF is less constructive because asset managers reduced net exposure and non-reportables remain elevated.
- S&P is mixed: asset-manager longs remain large, leveraged funds added shorts, and retail positioning is near an extreme.
- Quarterly rollover inflated open interest, so absolute contract changes carry more weight than weekly net/OI changes.

## Context & Methods

The notebook uses the local CFTC futures-only consolidated extracts refreshed through June 16, 2026. It compares the latest row with June 9, then joins the current expanding-window percentiles and regime labels.

### Key Assumptions

- TFF and Legacy are interpreted separately because their trader classifications overlap.
- Absolute long/short changes receive more weight in quarterly roll week than changes in net position as a share of open interest.

## Data

### 1. Load the refreshed COT extracts

In [1]:
from pathlib import Path
import pandas as pd

ROOT = Path('A:\\work\\trading\\cot report')
ANALYSIS = ROOT / 'analysis'
paths = {
    ('S&P 500','TFF'): ANALYSIS/'cot_exact_output'/'sp500_exact_consolidated_data_2016_2026.csv',
    ('NASDAQ-100','TFF'): ANALYSIS/'cot_exact_output'/'nq_exact_consolidated_data_2016_2026.csv',
    ('S&P 500','Legacy'): ANALYSIS/'cot_legacy_output'/'sp500_legacy_data_2016_2026.csv',
    ('NASDAQ-100','Legacy'): ANALYSIS/'cot_legacy_output'/'nq_legacy_data_2016_2026.csv',
}
freshness = []
for (market, report), path in paths.items():
    frame = pd.read_csv(path)
    freshness.append({'market': market, 'report': report, 'latest_date': frame['date'].iloc[-1], 'rows': len(frame)})
pd.DataFrame(freshness)

       market  report latest_date  rows
0     S&P 500     TFF  2026-06-16   524
1  NASDAQ-100     TFF  2026-06-16   546
2     S&P 500  Legacy  2026-06-16   524
3  NASDAQ-100  Legacy  2026-06-16   546

## Results

### 2. Latest positioning, flows, and historical percentiles

In [2]:
position_rows = pd.read_csv(ANALYSIS/'reports'/'cot_2026-06-16'/'position_rows.csv')
position_rows[['market','report','group','net','net_oi_pct','net_change','long_change','short_change','percentile']].round(2)

,market,report,group,net,net_oi_pct,net_change,long_change,short_change,percentile
0,S&P 500,TFF,Asset Manager,986577.0,37.59,-261.0,-5366.0,-5105.0,76.53
1,S&P 500,TFF,Dealer,-609648.0,-23.23,59630.0,13712.0,-45918.0,27.10
2,S&P 500,TFF,Leveraged Money,-523882.0,-19.96,-64192.0,-11545.0,52647.0,9.16
3,S&P 500,TFF,Other Reportable,22697.0,0.86,-12934.0,-8430.0,4504.0,84.92
4,S&P 500,TFF,Non-reportable,124255.0,4.73,17757.0,21918.0,4161.0,89.69
5,NASDAQ-100,TFF,Asset Manager,71133.0,18.96,-13304.0,-7357.0,5947.0,61.72
6,NASDAQ-100,TFF,Dealer,-31125.0,-8.29,3828.0,10003.0,6175.0,45.60
7,NASDAQ-100,TFF,Leveraged Money,-51468.0,-13.72,5286.0,-751.0,-6037.0,26.19
8,NASDAQ-100,TFF,Other Reportable,-2700.0,-0.72,696.0,-597.0,-1293.0,59.89
9,NASDAQ-100,TFF,Non-reportable,14160.0,3.77,3495.0,7977.0,4482.0,87.55
10,S&P 500,Legacy,Non-commercial,-180143.0,-6.86,14411.0,-5510.0,-19921.0,19.08
11,S&P 500,Legacy,Commercial,55887.0,2.13,-32169.0,338692.0,370861.0,71.18
12,S&P 500,Legacy,Non-reportable,124255.0,4.73,17757.0,21918.0,4161.0,89.69
13,NASDAQ-100,Legacy,Non-commercial,-20866.0,-5.56,-9885.0,863.0,10748.0,6.78
14,NASDAQ-100,Legacy,Commercial,6706.0,1.79,6390.0,19031.0,12641.0,79.67
15,NASDAQ-100,Legacy,Non-reportable,14160.0,3.77,3495.0,7977.0,4482.0,87.55

### 3. Regime labels and rollover check

In [3]:
regimes = pd.read_csv(ANALYSIS/'reports'/'cot_2026-06-16'/'current_regimes.csv')
meta = pd.read_csv(ANALYSIS/'reports'/'cot_2026-06-16'/'market_meta.csv')
display(regimes)
meta[['market','report','date','open_interest','open_interest_change','open_interest_change_pct','price_return_1w_pct']].round(2)

,market,report,report_date,score,bucket,trigger_detail
0,S&P 500,TFF,2026-06-16,0.5,Mixed,lev_money 9.2% +0.50 Leveraged Money underexposed
1,S&P 500,Legacy,2026-06-16,0.0,Mixed,NaN
2,NASDAQ-100,TFF,2026-06-16,-1.0,Mixed,non_reportable 87.5% -1.00 Non-reportable elev...
3,NASDAQ-100,Legacy,2026-06-16,2.5,Risk-On,noncommercial 6.8% +2.50 Non-commercial short ...

,market,report,date,open_interest,open_interest_change,open_interest_change_pct,price_return_1w_pct
0,S&P 500,TFF,2026-06-16,2624882.0,382878.0,17.08,1.69
1,NASDAQ-100,TFF,2026-06-16,375254.0,40464.0,12.09,3.04
2,S&P 500,Legacy,2026-06-16,2624882.0,382878.0,17.08,1.69
3,NASDAQ-100,Legacy,2026-06-16,375254.0,40464.0,12.09,3.04

## Takeaways

1. Nasdaq has stronger upside asymmetry than S&P because Legacy speculative shorts are historically crowded.
2. Nasdaq is not a clean structural long until TFF asset managers stop reducing exposure.
3. S&P is mixed and needs confirmation from leveraged-fund covering or genuine asset-manager selling.
4. Elevated non-reportable percentiles in both markets reduce the quality of an unhedged chase.